services:
  web:
    build:
      dockerfile: 'Dockerfile.dev'
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p ${RAILS_HOST_PORT} -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/app/.bundle
      - node_modules:/app/node_modules
      - yarn-cache:/app/.yarn-cache
    # ports:
    #   - "${RAILS_HOST_PORT}:${RAILS_HOST_PORT}"
    env_file:
      - "./.env"
    environment:
      - SELENIUM_REMOTE_HOST=selenium
    depends_on:
      - selenium
  css:
    build:
      dockerfile: 'Dockerfile.dev'
    volumes:
      - .:/app
      - bundle:/app/.bundle
      - node_modules:/app/node_modules
      - yarn-cache:/app/.yarn-cache
    tty: true

    env_file:
      - "./.env"
    command: "bin/rails themed_tailwindcss:watch"
  js:
    build:
      dockerfile: 'Dockerfile.dev'
    volumes:
      - .:/app
      - bundle:/app/.bundle
      - node_modules:/app/node_modules
      - yarn-cache:/app/.yarn-cache
    tty: true
    env_file:
      - "./.env"
    command: "bin/shakapacker -w"

  selenium:
    image: selenium/standalone-chrome:latest
    platform: linux/amd64
    environment:
      - SE_VNC_NO_PASSWORD=true
      - VNC_NO_PASSWORD=true
      - SCREEN_WIDTH=1500
      - SCREEN_HEIGHT=900
    # ports: CI doesn't need to expose ports.
    #   - 4444:4444
    #   - 5900:5900
    #   - 7900:7900

volumes:
  bundle:
  node_modules:
  yarn-cache:
