services:
  web:
    build:
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    command: run
    restart: unless-stopped
    volumes:
      - ./app-data:/usr/src/app/app-data
    environment:
     - DEFAULT_HOST_URL=http://localhost:3001
    ports:
      - 3001:3000
