# Rails loads items on shared keys for all environments
shared:
  - key: "amethyst-moon"
    mode: "light"
    showcase_colors:
      - "rgb(248 250 252)"
      - "rgb(219 234 254)"
      - "rgb(99 102 241)"
      - "rgb(16 185 129)"
    color_suggestions:
      - "#63f263"
      - "#f1ef63"
      - "#f16365"
      - "#63acf1"
      - "#cc63f2"
      - "#f2c063"
  - key: "frost-crystal"
    mode: "light"
    showcase_colors:
      - "rgb(255 255 255)"
      - "rgb(219 234 254)"
      - "rgb(59 130 246)"
      - "rgb(207 250 254)"
    color_suggestions:
      - "#3bf5a1"
      - "#ebf53b"
      - "#f53e3b"
      - "#3bf5d9"
      - "#d33bf5"
      - "#f56c3b"
  - key: "noir-flow"
    mode: "dark"
    showcase_colors:
      - "#151622"
      - "#2a2b44"
      - "#00a5a5"
      - "#a949b6"
    color_suggestions:
      - "#006124"
      - "#5e6100"
      - "#610000"
      - "#003061"
      - "#3d0061"
      - "#613700"
  - key: "kernel-mindset"
    mode: "dark"
    showcase_colors:
      - "#242521"
      - "#5e6da1"
      - "#8269be"
      - "#baa966"
    color_suggestions:
      - "#61a15d"
      - "#a1a15d"
      - "#a15d5d"
      - "#5d7ea1"
      - "#895da1"
      - "#a17c5d"
