# Rails loads items on shared keys for all environments
shared:
  - key: "amethyst-moon"
    showcase_colors:
      - "rgb(248 250 252)"
      - "rgb(219 234 254)"
      - "rgb(99 102 241)"
      - "rgb(16 185 129)"
  - key: "frost-crystal"
    showcase_colors:
      - "rgb(255 255 255)"
      - "rgb(219 234 254)"
      - "rgb(59 130 246)"
      - "rgb(207 250 254)"
  - key: "noir-flow"
    showcase_colors:
      - "#0c0c0b"
      - "#30312c"
      - "#b1b1af"
  - key: "kernel-mindset"
    showcase_colors:
      - "#242521"
      - "#5e6da1"
      - "#8269be"
      - "#baa966"
